Refactor replace_tokens and create a replace_token function to capture duplicated logic

diff --git a/bin/discord b/bin/discord
--- a/bin/discord
+++ b/bin/discord
@@ -123,6 +123,17 @@ get_response_header() {
     echo "$2" | grep -E "^$1:" | sed "s/^[^:]*: //"
 }
 
+replace_token() {
+    log_debug "Replacing \"$2\" tag..."
+
+    if [ -z "${!3}" ]
+    then
+        log_error "Missing required option $4"
+        exit 1
+    fi
+
+    echo "$1" | sed "s/$2/${!3}/"
+}
 
 replace_tokens() {
     log_debug "Calling replace_tokens..."
@@ -130,80 +141,45 @@ replace_tokens() {
     path="$1"
     if echo $path | grep -q "{guild.id}"
     then
-        log_debug "Replacing guild tag..."
-        validate_opts "OPTS_GUILD" "-g|--guild"
-        path="$(echo "$path" | sed "s/{guild.id}/$OPTS_GUILD/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{guild.id}" "OPTS_GUILD" "-g|--guild")
     fi
 
     if echo $path | grep -q "{channel.id}"
     then
-        log_debug "Replacing channel tag..."
-        validate_opts "OPTS_CHANNEL" "-c|--channel"
-        path="$(echo "$path" | sed "s/{channel.id}/$OPTS_CHANNEL/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{channel.id}" "OPTS_CHANNEL" "-c|--channel")
     fi
 
     if echo $path | grep -q "{user.id}"
     then
-        log_debug "Replacing user tag..."
-        validate_opts "OPTS_USER" "-u|--user"
-        path="$(echo "$path" | sed "s/{user.id}/$OPTS_USER/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{user.id}" "OPTS_USER" "-u|--user")
     fi
 
     if echo $path | grep -q "{message.id}"
     then
-        log_debug "Replacing message tag..."
-        validate_opts "OPTS_MESSAGE" "-m|--message"
-        path="$(echo "$path" | sed "s/{message.id}/$OPTS_MESSAGE/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{message.id}" "OPTS_MESSAGE" "-m|--message")
     fi
 
     if echo $path | grep -q "{webhook.id}"
     then
-        log_debug "Replacing webhook tag..."
-        validate_opts "OPTS_WEBHOOK" "-w|--webhook"
-        path="$(echo "$path" | sed "s/{webhook.id}/$OPTS_WEBHOOK/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{webhook.id}" "OPTS_WEBHOOK" "-w|--webhook")
     fi
 
     if echo $path | grep -q "{integration.id}"
     then
-        log_debug "Replacing integration tag..."
-        validate_opts "OPTS_INTEGRATION" "-i|--integration"
-        path="$(echo "$path" | sed "s/{integration.id}/$OPTS_INTEGRATION/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{integration.id}" "OPTS_INTEGRATION" "-i|--integration")
     fi
 
     if echo $path | grep -q "{overwrite.id}"
     then
-        log_debug "Replacing overwrite tag..."
-        validate_opts "OPTS_OVERWRITE" "-o|--overwrite"
-        path="$(echo "$path" | sed "s/{overwrite.id}/$OPTS_INTEGRATION/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{overwrite.id}" "OPTS_OVERWRITE" "-o|--overwrite")
     fi
 
     if echo $path | grep -q "{emoji}"
     then
-        log_debug "Replacing emoji tag..."
-        validate_opts "OPTS_EMOJI" "-e|--emoji"
-        path="$(echo "$path" | sed "s/{emoji}/$OPTS_EMOJI/")"
-        log_debug "Path updated \"$path\""
+        path=$(replace_token "$path" "{emoji}" "OPTS_EMOJI" "-e|--emoji")
     fi
 
     echo $path
-}
-
-validate_opts() {
-    variable="$1"
-    opts="$2"
-
-    if [ -z "${!variable}" ]
-    then
-        log_error "Missing required option ${opts}"
-        exit 1
-    fi
 }
 
 # This is required. This can either be a bot token or a user token. Using the
